# Generated by Django 3.1.6 on 2021-02-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BaseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['-slug', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BaseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.basequestion')),
                ('date_submitted', models.DateField(blank=True, db_index=True, null=True)),
                ('date_entered', models.DateField(blank=True, db_index=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=256)),
            ],
            bases=('polls.basequestion',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('basetopic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.basetopic')),
                ('date_submitted', models.DateField(blank=True, db_index=True, null=True)),
                ('field1', models.CharField(blank=True, max_length=256)),
            ],
            bases=('polls.basetopic',),
        ),
        migrations.CreateModel(
            name='QuestionContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('contributor', 'Contributor')], default='contributor', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='polls.contributor')),
                ('base_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.basequestion')),
            ],
            options={
                'ordering': ['role', 'contributor__display_name', 'base_question__title'],
            },
        ),
        migrations.AddField(
            model_name='basequestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.basetopic'),
        ),
    ]
